// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InteractionType string

const (
	InteractionTypeLike   InteractionType = "like"
	InteractionTypeRepost InteractionType = "repost"
)

func (e *InteractionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InteractionType(s)
	case string:
		*e = InteractionType(s)
	default:
		return fmt.Errorf("unsupported scan type for InteractionType: %T", src)
	}
	return nil
}

type NullInteractionType struct {
	InteractionType InteractionType
	Valid           bool // Valid is true if InteractionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInteractionType) Scan(value interface{}) error {
	if value == nil {
		ns.InteractionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InteractionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInteractionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InteractionType), nil
}

type Follow struct {
	ID        int32
	UriKey    string
	AuthorID  int32
	SubjectID int32
	CreatedAt pgtype.Timestamp
}

type Interaction struct {
	ID           int32
	UriKey       string
	AuthorID     int32
	Kind         InteractionType
	PostUriKey   string
	PostAuthorID int32
	CreatedAt    pgtype.Timestamp
}

type Post struct {
	ID          int32
	UriKey      string
	AuthorID    int32
	ReplyParent []string
	ReplyRoot   []string
	Language    pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type SubscriptionState struct {
	ID      int32
	Service string
	Cursor  int64
}

type TmpFollow struct {
	ID        int32
	UriKey    string
	AuthorID  int32
	SubjectID int32
	CreatedAt pgtype.Timestamp
}

type TmpInteraction struct {
	ID           int32
	UriKey       string
	AuthorID     int32
	Kind         InteractionType
	PostUriKey   string
	PostAuthorID int32
	CreatedAt    pgtype.Timestamp
}

type TmpPost struct {
	ID          int32
	UriKey      string
	AuthorID    int32
	ReplyParent []string
	ReplyRoot   []string
	Language    pgtype.Text
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID             int32
	Did            string
	Handle         pgtype.Text
	FollowersCount pgtype.Int4
	FollowsCount   pgtype.Int4
	PostsCount     pgtype.Int4
	LastUpdate     pgtype.Timestamp
}
