services:
  api:
    build:
      context: .
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    command: sh ./run.sh
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_init:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    ports:
      - "6379:6379"