global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bsky-feed'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'api:3333' ]

  - job_name: 'db'
    static_configs:
      - targets: [ 'db-exporter:9187' ]