CREATE TEMPORARY TABLE tmp_interactions
    ON COMMIT DROP
AS
SELECT *
FROM interactions
    WITH NO DATA;

CREATE TEMPORARY TABLE tmp_posts
    ON COMMIT DROP
AS
SELECT *
FROM posts
    WITH NO DATA;

CREATE TEMPORARY TABLE tmp_follows
    ON COMMIT DROP
AS
SELECT *
FROM follows
    WITH NO DATA;