// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: languages.sql

package db

import (
	"context"
)

const createLanguage = `-- name: CreateLanguage :one
INSERT INTO languages (code)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateLanguage(ctx context.Context, code string) (int32, error) {
	row := q.db.QueryRow(ctx, createLanguage, code)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getLanguage = `-- name: GetLanguage :one
SELECT id
FROM languages
WHERE code = $1
`

func (q *Queries) GetLanguage(ctx context.Context, code string) (int32, error) {
	row := q.db.QueryRow(ctx, getLanguage, code)
	var id int32
	err := row.Scan(&id)
	return id, err
}
