// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Language struct {
	ID   int32
	Code string
}

type Post struct {
	Uri         string
	AuthorDid   pgtype.Text
	Cid         string
	ReplyParent pgtype.Text
	ReplyRoot   pgtype.Text
	IndexedAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
}

type PostLanguage struct {
	ID         int32
	PostUri    pgtype.Text
	LanguageID pgtype.Int4
}

type SubscriptionState struct {
	ID      int32
	Service string
	Cursor  int64
}

type User struct {
	Did            string
	Handle         pgtype.Text
	FollowersCount pgtype.Int4
	FollowsCount   pgtype.Int4
	PostsCount     pgtype.Int4
	IndexedAt      pgtype.Timestamp
	LastUpdate     pgtype.Timestamp
}
