// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: post_languages.sql

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreatePostLanguagesParams struct {
	PostUri    pgtype.Text
	LanguageID pgtype.Int4
}
