apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsky-feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsky-feed
      component: api
  template:
    metadata:
      labels:
        app: bsky-feed
        component: api
    spec:
      containers:
        - name: api
          image: ealmuina/bsky-feed:latest
          envFrom:
            - secretRef:
                name: bsky-feed-secrets
          command: [ "./run_api.sh" ]
          volumeMounts:
            - mountPath: /app/db
              name: sqlite-volume
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: bsky-feed-sqlite-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: bsky-feed-api
spec:
  type: NodePort
  ports:
    - port: 3333
      targetPort: 3333
      nodePort: 30033
  selector:
    app: bsky-feed
    component: api