{
 "title": "Firehose",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New accounts per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(firehose_events_total{recordType=\"app.bsky.actor.profile\", operationType=\"create\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregated Firehose events per minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(firehose_events_total{recordType=~\"app.bsky.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event processing time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(firehose_event_processing_duration_seconds_bucket{recordType=~\"app.bsky.feed.like|app.bsky.feed.post|app.bsky.feed.repost|app.bsky.graph.follow\", operationType=~\"create|update|delete\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firehose events per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(firehose_events_total{recordType=~\"app.bsky.*\"}[1m])",
     "legendFormat": "{{recordType}}"
    }
   ]
  }
 ]
}